[build-system]
requires = [
    "setuptools>=45",
    "wheel>=0.37.0",
    "setuptools_scm>=6.2",
    "pytest>=5,<8",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"
write_to = "volkswagencarnet/version.py"